### ISSUE TITLE
The same data binding to components

### ISSUE THREAD

**Issue by ndovnar** [JonWatkins/vue-runtime-template-compiler#3]
Hello, first of all, thanks a lot for your job!
The problem, when you use a template compiler with `v-for` it passes data from the first item from array to all components. 

I noticed that this problem appears in the latest version, in 1.1.1 it works.
here's a reproduction of the problem https://codesandbox.io/s/vue-runtime-template-compiler-9pywv?file=/src/App.vue.

**Comment by seliquity** [comment]
I think I have the same issue, I end up with the same component data due to passing object props.

It seems the compile() method uses a custom merge() function to fill in the new component, but it doesn't pass the "deep" flag and so just does an Object.assign() shallow copy which isn't sufficient in all cases.
